### ISSUE TITLE
ZMNHVD1 Flush Dimmer 0-10V - On/Off doesn't work correctly.

### ISSUE THREAD

**Issue by SkorpionNL** [athombv/com.qubino#15]
When switching On/Off the module icon goes to On or Off (greyed out) but it doesn't change the real state. For example when level = 100, in Homey interface or flow when module is turned off, module stays on at level 100. Module only goes off when dim level is changed to 0 for example.

Qubino app version: v1.1.2
Homey version: V1.1.9

**Comment by RobinBol** [comment]
This should be fixed in app version 1.1.4, if not please re-open this issue!
