### ISSUE TITLE
Qubino Flush Dimmer ZMNHDDx status not updated using pulse switch

### ISSUE THREAD

**Issue by ivleth** [athombv/com.qubino#16]
Hello, it seems that the on/off state is not updated when using a pulse switch, however the dimmer level is working. To replay:

1 .dimmer is off
2. turn on the dimmer within Homey on the devices screen, the icon gets activated.
3. operate the dimmer via the pulse switch, the level is updated on the devices screen
4. turn off the dimmer via the pulse switch... the icon stays activated

pulse switch is connected to i1, diagram: http://qubino.com/download/990/

**Comment by RobinBol** [comment]
Note to self: set correct association group and add report parser to onoff for correct command.

**Comment by RobinBol** [comment]
Should be fixed in app version 1.1.4, if not please re-open this issue!
