### ISSUE TITLE
 Qubino Flush Shutter DC ZMNHOD1 

### ISSUE THREAD

**Issue by ruudcornelisse** [athombv/com.qubino#17]
zou het mogelijk zijn om de Qubino Flush Shutter DC ZMNHOD1  12-24v gelijkstroommotoren toe te voegen? informatie; http://qubino.com/products/flush-shutter-dc/ handleiding kan hier worden gevonden: qubino.com/download/1055/ veel dank!

**Comment by RobinBol** [comment]
Sorry, there seem to be some issues with these modules. We have some at the office and they don't work according to the Z-Wave specification, see also this thread: https://github.com/athombv/homey/issues/1317#issuecomment-287067832.

**Comment by Merlinuf** [comment]
hi,
isnt this fixed yet ?
