### ISSUE TITLE
ZMNHWD1 RGBW Dimmer Plus Support

### ISSUE THREAD

**Issue by ArchiSpec** [athombv/com.qubino#18]
Hi - can you please advise if support for the RGBW Dimmer Plus module will be added soon?

Thanks in advance!

**Comment by RobinBol** [comment]
Hi, this is not on our short term roadmap at the moment. I'll leave the issue here as a reminder to implement the device.

**Comment by ArchiSpec** [comment]
Hi, just to bump this - any chance of it moving up the priority list?

Thanks.

**Comment by ArchiSpec** [comment]
Sorry, above reference was in error but cannot remove the reference now.

Any chance of the ZMNHWD1 RGBW unit being added any time soon?>

Thanks in advance.

**Comment by RobinBol** [comment]
Minor update; we have the device add will be working on adding support for it.

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2557
