### ISSUE TITLE
Support for flush shutters HCD1 and HOD

### ISSUE THREAD

**Issue by cbho** [athombv/com.qubino#20]
What are the perspectives regarding support to the HCD1- and HOD1-modules?
Asked at the app store, but not sure if it is read?

By coincidence I found this:
https://github.com/clandmeter/com.qubino.shutter
What are the issues? Will it work if I buy a the "Flush shutter DC - Gen" that's in the stores now?
Regards,
Chr.

**Comment by Merlinuf** [comment]
Have all development stopped on this?

**Comment by jogegot** [comment]
Any update ??

**Comment by RobinBol** [comment]
Closing as duplicate of https://github.com/athombv/com.qubino/issues/22. That issue has an answer to your question.
