### ISSUE TITLE
switching device on through setting the brightness doesn't set "status on"

### ISSUE THREAD

**Issue by ivleth** [athombv/com.qubino#21]
Hi, I am using Qubino dimmers ZMNHDD1 to switch my lights on and off. What I do is, based on the time of the day,  I turn on the lights with setting the brightness instead of switching it on first. I do this like this because during the day the lights are running at a 100% and during the night at 20%. If I would turn on the light at night first and then set the brightness, I would get blinded ;-)

This approach works perfectly for me but the downside is that the lights won't get the "on" status. The device icon stays grayed out.

for screenshots, see https://forum.athom.com/discussion/3942/switching-device-on-through-setting-the-brightness-doesnt-set-status-on

**Comment by RobinBol** [comment]
Thanks for reporting, just to let you know; this will be fixed soon, there will be an update for the Qubino app in the near future.

**Comment by ArchiSpec** [comment]
Likewise look forward to this refinement.

**Comment by ivleth** [comment]
Hi Robin, any idea when this is expected? I use now the energy label to detect if lights are on, but that doesn't seem to be reliable :-|

I will however make a fork and see if I can fix it myself in the meanwhile,

Thanks!

**Comment by ArchiSpec** [comment]
@RobinBol Just to second @ivleth 's comment. 
**Also, will the update include support for the RGBW dimmer module?**

**Comment by RobinBol** [comment]
Sorry, we expected that the rewrite to SDKv2 would be quicker, but it is taking more time. I'll updat e again when we get to it!

**Comment by RobinBol** [comment]
Hi! I just published an update of the Qubino app (beta), it has been rewritten to SDKv2 and includes many minor improvements. The device should now be updated to the 'on' status after you turned it on via dimming! Please let me know if you have any additional questions or problems.
