### ISSUE TITLE
Support for ZMNHOD1?

### ISSUE THREAD

**Issue by Krisstenswe** [athombv/com.qubino#22]
Is there any chance the Quibino-app will support ZMNHOD1 in the near future?
Regards

**Comment by RobinBol** [comment]
Yes, this will come in the near future.

**Comment by Krisstenswe** [comment]
Great - Thanks!

**Comment by willumpie82** [comment]
Hi all, is there any progress on this issue? 
When you're in the process of adding the Qubino shutter devices, please also include the ZMNHCDx, this device only differs in ID, parameters and functions are the same.  (I checked the openzwave implementation of these device ). 

For now I used the https://github.com/clandmeter/com.qubino.shutter repo and added it myself. It's recognized but the app crashes when I want to control it, changing settings (e.g. activate calibration) work though. Unfortunately that repo is not maintained.

**Comment by jolny** [comment]
ZMNHCDx is not the same device though, it controls AC motors while ZMNHODx controls DC motors. So they should be added as separate devices.

**Comment by willumpie82** [comment]
That is correct, but the parameter set is identical. so it should not be to much of an effort to introduce both at the same time.

**Comment by krillehbg** [comment]
Is this going to be supported soon? In October you wrote it's going to be in the near future but haven't heard anything about this yet?

**Comment by vk900** [comment]
Good question, I've got a HOD laying around for months already, awaiting whenever this is supported..

**Comment by Merlinuf** [comment]
When Will the dc shutter get added?

**Comment by Merlinuf** [comment]
@robinbol do you have s time?

**Comment by Merlinuf** [comment]
?

**Comment by RobinBol** [comment]
@Merlinuf, yes we are working on updating the qubino app at the moment.

**Comment by Merlinuf** [comment]
Ok when Will the shutter work?


Med vänlig hälsning,

Kristoffer Persson

**Comment by RobinBol** [comment]
Sorry we do not communicate timelines, bur I am working on it at the moment.

**Comment by willumpie82** [comment]
@RobinBol will the ZMNHCDx shutter controller also included? Can you give us an update (in a bit more detail ) on the progress?

**Comment by RobinBol** [comment]
I just published a beta version of the Qubino app, it has been rewritten to SDKv2 and many minor improvements have been added. Also the two roller shutters (ZMNHOD and ZMNHCD) have been added. Thanks for reporting and please let me know if you have any additional questions or problems!
