### ISSUE TITLE
Missing parameters for ZMNHDD1

### ISSUE THREAD

**Issue by johkin** [athombv/com.qubino#23]
When adding ZMNHDD1 do Homey, I couldn't find the "Enable double click function" in the configuration of the device. After some more investigation I found that there are several parameters missing in the configuration.
I'm trying to fix this and create a PR in the coming days.

**Comment by johkin** [comment]
I tried to add the missing parameters, but when trying out this on my Homey the new parameters (dropdowns) didn't show up. I modified 'driver.js' and 'ZMNHDD1.json', are there anything else that needs to be done?

**Comment by Steunzool1** [comment]
put 21,1,1 in expert parameters , and double click will work.
Any luck in using button 2 ? (i can't get it to work)

**Comment by johkin** [comment]
Yes, the "raw parameters" is what I'm using right now (which is very good that it exists).
I finally managed to get a local implementation working, but now the configuration is defined three times in the app.
I'm still looking for a good description of how a driver should be implemented, feels kind of awkward to duplicate the configuration several times.

I haven't tried to use button 2 yet, but it would be nice to have the possibility!

**Comment by RobinBol** [comment]
HI, thanks for reporting your issue. The Qubino app has just been updated with an SDKv2 rewrite (beta) and I added most, if not all, missing configuration parameters. Please let me know if you have any additional questions or problems.
