### ISSUE TITLE
Optional Qubino temperature sensor only reports temperature once after add device 

### ISSUE THREAD

**Issue by IngmarHallie** [athombv/com.qubino#24]
The optional external temperature sensor only reports the temperature once when the Qubino device is added.

Temperature changes are not displayed nor visible in Insights or Flow.

As if Homey doesn't process the send temperature updates.
This issues looks the same as i1 and i2 not reporting. See issue [here](https://github.com/athombv/com.qubino/issues/14)

Temps and i1 and i2 settings do report correctly on my Vera Controller.

**Comment by leim1234** [comment]
I am experiencing the same issue as mentioned here.
Will there be a fix for this?

**Comment by titanium87** [comment]
Same problem here with a 2 relay device.
Only once, then no more updates.

**Comment by RobinBol** [comment]
Hi all, thanks for reporting your issues. I just published a beta update of the Qubino app (SDKv2 rewrite amongst other improvements), please update to this version of the app and re-pair your devices. Then let me know whether the issue still persists or if it has been solved in the mean time!

**Comment by titanium87** [comment]
Thank you !  Just updated and re-paired..
Ill give you an update in a few hours :)

**Comment by titanium87** [comment]
It's now been over 1 hour.
Looks like it works great now :)

Thank you so much.  Just hoping it still works tomorrow ;)

**Comment by RobinBol** [comment]
Thanks for the feedback, closing this issue!
