### ISSUE TITLE
Setting automatic off time-out time from flowcard

### ISSUE THREAD

**Issue by emsa23** [athombv/com.qubino#28]
It would be nice to be able to set the "automatic off" time from flowcard.

Typical use case would be lamps that should go off after a specific time using the build-in qubino "automatic off" is then convenient. 

However if you like to the time-out to be different during different time of day then adjusting the timeout via flowcard would be nice.

**Comment by RobinBol** [comment]
Thanks for reporting. Just an idea, you could also just create a Flow that turns the device off after a specified time (which can depend on the time of day) after it has been turned on.

**Comment by RobinBol** [comment]
Hi! With regard to my previous comment, I am going to close this issue. The feature you request is also very well usable through the Flow Editor so it is unlikely we will add support for changing the automatic off time from a Flow Card. Anyway, thanks for your suggestion!
