### ISSUE TITLE
Support for ZMNHID Flush On/Off Thermostat 

### ISSUE THREAD

**Issue by JTThe** [athombv/com.qubino#30]
Feature request
When I check the Qubino App and supported devices, the ZMNHID1 is still missing.
qubino.com/products/flush-onoff-thermostat/

**Comment by lthierry** [comment]
Would be great if ZMNHID1 could be supported.... I bought several of them to control some infrared panels.

Product information: http://qubino.com/products/flush-onoff-thermostat/
Quick manual: http://qubino.com/download/1061/
Extended manual: http://qubino.com/download/2060/

@RobinBol, any idea when you will implement this? Could I be of any help?

**Comment by ronald2404** [comment]
Hi RobinBol, 

Do you have any idea when ZMNHID1  support will be included. I tried to add it to my homey but no succes here.  Thanks a lot!

**Comment by ronald2404** [comment]
Thanks for the update Robin.
Hopefully this can be up and running before the winter.

Regards Ronald

Op ma 2 jul. 2018 16:26 schreef Robin Bolscher <notifications@github.com>:

**Comment by lthierry** [comment]
Thanks, Robin. I agree with Ronald. I actually even hope it's available
before we have the first chilly days in September ;-)
Best, Leonard

Op ma 2 jul. 2018 22:38 schreef ronald2404 <notifications@github.com>:

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2556

**Comment by RobinBol** [comment]
Update: the App has just been updated to 2.0.3 (beta) which adds support for the ZMNHID, please let me know here athombv/homey#2556 if you have any feedback!

**Comment by ronald2404** [comment]
Hi Robin, that is great news. I am currently on holiday and need to change
my installation before I can test it so this will take some time.

Best regards Ronald

Op do 2 aug. 2018 13:32 schreef Robin Bolscher <notifications@github.com>:

**Comment by RobinBol** [comment]
Please let me know the results of your tests! And beware, you have to re-pair the devices if you install the beta app over the stable app.

**Comment by ronald2404** [comment]
Will do so, but this Will take some time.

Op vr 10 aug. 2018 11:54 schreef Robin Bolscher <notifications@github.com>:
