### ISSUE TITLE
change brightness over time

### ISSUE THREAD

**Issue by fredagscola** [athombv/com.qubino#31]
Hi,

Could we have the change brightness over time card as used in fibaro app and hue app i believe.

Thanks

**Comment by RobinBol** [comment]
It appears that the qubino devices do not support this.

Will keep this issue open as a reminder.

**Comment by RobinBol** [comment]
I discussed with the Qubino technical support, and it seems that the dimmer modules do support changing brightness over time, this will likely be supported in the upcoming re-write of the app.

**Comment by fredagscola** [comment]
Nice! Looking forward to it.

**Comment by RobinBol** [comment]
Hi! Thanks for your patience, I just published a beta version of the updated Qubino app. It should be possible to set a 'dim over time' attribute in the Flow Editor! I am closing this issue for now, I you have any further questions or problems please let us know!
