### ISSUE TITLE
ZMNHODx: Setttings: Invert shutter movement... - Doesn't work

### ISSUE THREAD

**Issue by Krisstenswe** [athombv/com.qubino#38]
Hi!
When I check the box for "Invert shutter movement direction" it doesn't change direction. The only thing that's happening is that there are no movement at all. If I change back (unbox), the shutter is moving again. It's like that setting would be labeled "Disable shutter movement"...

Homey 1.5.11
Qubino app 2.0.4
Device ZMNHOD1

**Comment by RobinBol** [comment]
Thank you for reporting your issue. Currently the App repository issue trackers are not being monitored, all (App related) issues should be reported at https://github.com/athombv/homey/issues. Alternatively, use the 'Report an issue' button on the App page in the Homey Apps store to create an issue at the correct location. This issue will be closed now, our apologies for the inconvenience.

**Comment by Krisstenswe** [comment]
---
