### ISSUE TITLE
New release please in the appstore

### ISSUE THREAD

**Issue by gruijter** [athombv/com.qubino#7]
Hi Robin,

I have been waiting a long time already for a new version to appear in the appstore. There v1.0.3 is still active, whereas the device I have is only supported in the later unpublished version. I now have it sideloaded, but would really like to use the official appstore version to prevent potential problems with Homey.

Could you please publish a new version?

Much appreciated :)

**Comment by clandmeter** [comment]
Could somebody @RobinBol or @WeeJeWel explain why its taking so long (**more then 6 months**) to upload a new release of this app?  This app has been developed by @kasteleman and was requested by athmobv to be moved to the offical athombv repositories so athom could pickup development. It has received some love from @RobinBol but this has never resulted to any update of the app.

If athom is currently limited in time wouldn't it be better to move this module back to the community and let us create a new release/releases and when the time comes athom can merge the changes back?

**Comment by RobinBol** [comment]
We are not holding anyone from the community back to continue developing this app, even better; the current Qubino app in the app store is the one from @kasteleman. We have been busy trying to implement all functionality for the Qubino devices before releasing the app, unfortunately we have hit an issue which will take some time to resolve and will prevent 500 series modules to use the i2/i3 functionality in the Flow editor. We were trying to fix that in the mean time but seems to take a bit more time and will be pushed back a bit on our roadmap. You can expect a (minor) update of the app in the coming weeks (without 500 series i2/i3).

P.S. we don't prevent the community from forking this app to continue development! It would be greatly appreciated.

**Comment by kasteleman** [comment]
It isn't the 500 series (zwave plus) only. My non zwave plus HDA2 (flush dimmer) isn't responding on i2/i3. There is a log in the zwave debug: Received application command for COMMAND_CLASS_MULTI_CHANNEL, data: 0x06013003ff followed with 0x0601300300.
It was responding in open zwave.

**Comment by RobinBol** [comment]
Update is pushed to the app store, if you have remarks or improvements please let me know!
